### PR TITLE
Regex fixes

### PR DESCRIPTION
**Pull request by delirious-lettuce**

### CODE REVIEW

**Comment by Ekultek** [comment]
If nothing is heard back in 48 hours I'll close this as no reply

**Comment by delirious-lettuce** [comment]
https://regex101.com/r/Lc7qvZ/1

> ***"{1} Quantifier — Matches exactly one time (meaningless quantifier)"***

> ["Characters can be listed individually, e.g. `[amk]` will match `'a'`, `'m'`, or `'k'`."](https://docs.python.org/2/library/re.html#regular-expression-syntax)
---
https://regex101.com/r/uGHp84/1

> ***"\\{ matches the character { literally (case sensitive)"***
> ***"{ matches the character { literally (case sensitive)"***

**Comment by Ekultek** [comment]
```
>>> wordpress_hash = re.compile("^\$[\w.]\$\w+\$\S{22}$")
>>> wordpress_hash_list = [
	"$P$9aD9ZLmkpsN4A83G8MefaaP888gVKX0",
        "$P$984478476IagS59wHZvyQMArzfx58u.",
        "$P$D0bvd1k4$6v8qlQdP4boGl8vOtgbzL0",
        "$1$STLDxaNZ$CUa39AASTza8HpYF1trFR.",
        "$1$Xuxygilk$DoASOA3PL2uw3WqOT8Ak10"
	]
>>> for i, item in enumerate(wordpress_hash_list):
	if wordpress_hash.match(item):
		print("[{}] Matched -> {}".format(i, item))
	else:
		print("[{}] Did not match -> {}".format(i, item))

		
[0] Did not match -> $P$9aD9ZLmkpsN4A83G8MefaaP888gVKX0
[1] Did not match -> $P$984478476IagS59wHZvyQMArzfx58u.
[2] Matched -> $P$D0bvd1k4$6v8qlQdP4boGl8vOtgbzL0
[3] Matched -> $1$STLDxaNZ$CUa39AASTza8HpYF1trFR.
[4] Matched -> $1$Xuxygilk$DoASOA3PL2uw3WqOT8Ak10
>>> 
```

Your regular expression doesn't match correctly.

**Comment by delirious-lettuce** [comment]
You forgot to test against your own original...

```
>>> wordpress_hash = re.compile("^\$[\w.]{1}\$\w+\$\S{22}$")
>>> wordpress_hash_list = [
...     "$P$9aD9ZLmkpsN4A83G8MefaaP888gVKX0",
...         "$P$984478476IagS59wHZvyQMArzfx58u.",
...         "$P$D0bvd1k4$6v8qlQdP4boGl8vOtgbzL0",
...         "$1$STLDxaNZ$CUa39AASTza8HpYF1trFR.",
...         "$1$Xuxygilk$DoASOA3PL2uw3WqOT8Ak10"
...     ]
>>> for i, item in enumerate(wordpress_hash_list):
...     if wordpress_hash.match(item):
...             print("[{}] Matched -> {}".format(i, item))
...     else:
...             print("[{}] Did not match -> {}".format(i, item))
... 
[0] Did not match -> $P$9aD9ZLmkpsN4A83G8MefaaP888gVKX0
[1] Did not match -> $P$984478476IagS59wHZvyQMArzfx58u.
[2] Matched -> $P$D0bvd1k4$6v8qlQdP4boGl8vOtgbzL0
[3] Matched -> $1$STLDxaNZ$CUa39AASTza8HpYF1trFR.
[4] Matched -> $1$Xuxygilk$DoASOA3PL2uw3WqOT8Ak10

```

**Comment by Ekultek** [comment]
@delirious-lettuce it doesn't matter. I'm aware of the original, but if you're going to open a pull request on regular expressions I expect it to be a improvement on performance, reliability, or just a better regular expression. I am sorry but regular expressions are not easy to come up with for these hashes and I am going to be extremely strict on them. I'll leave this open for 48 hours to give you time to either come up with a new one, or close this.

**Comment by delirious-lettuce** [comment]
@Ekultek ,

Removing unnecessary quantifiers is better...

Also, if you were ***extremely strict***, why doesn't your original regular expression work?

**Comment by Ekultek** [comment]
@delirious-lettuce closed.

**Comment by Ekultek** [comment]
@delirious-lettuce obviously it does, but as I said ` I expect it to be a improvement on performance, reliability, or just a better regular expression`

**Comment by delirious-lettuce** [comment]
@Ekultek ,

By your own definition it is better. You seem to be having trouble writing regular expressions, why add unnecessary complications to them?

**Comment by Ekultek** [comment]
Thank you for your pull requests, the other one was merged.

**Pull request closed without merging**
