### PR TITLE
Remove unnecessary second regex check

### PR DESCRIPTION
**Pull request by delirious-lettuce**
In some cases, `regex.match(hash_to_verify)` is being run twice unnecessarily.

* when `regex` doesn't match
* when `regex` matches and `least_likely=False`

This PR fixes that issue.

### CODE REVIEW

**Comment by Ekultek** [comment]
Let me push to the repo before merging it

**Comment by Ekultek** [comment]
Fix the conflicts for the new `verbose` flag and I'll merge it

**Comment by delirious-lettuce** [comment]
@Ekultek ,

Ok, let me take a quick look.

**Comment by Ekultek** [comment]
Sounds good

**Comment by delirious-lettuce** [comment]
@Ekultek ,

I'm not sure about your commit.

```python
    for regex in HASH_TYPE_REGEX:
        if verbose is True:
            LOGGER.debug("Testing: {}".format(HASH_TYPE_REGEX[regex]))
        if regex.match(hash_to_verify) and least_likely:
            if verbose is True:
                LOGGER.debug("Testing: {}".format(HASH_TYPE_REGEX[regex]))
            return HASH_TYPE_REGEX[regex]
        elif regex.match(hash_to_verify) and not least_likely:
            if verbose is True:
                LOGGER.debug("Testing: {}".format(HASH_TYPE_REGEX[regex]))
            return HASH_TYPE_REGEX[regex][0]
```

The `if verbose is True` part is repeated twice with the same message. I'm not sure why the second message (inside if there is a regex match) is even needed...?

Also, I was reading PEP8 again yesterday and noticed that it is frowned upon to use `is True` for a boolean.

> Yes:
> if greeting:

> No:
> if greeting == True:

> Worse:
> if greeting is True:

https://pep8.org/#programming-recommendations

**Comment by delirious-lettuce** [comment]
I could write it like this:

```python
for regex, hash_types in HASH_TYPE_REGEX.iteritems():
    if verbose:
        LOGGER.debug("Testing: {}".format(hash_types))
    if regex.match(hash_to_verify):
        return hash_types if least_likely else hash_types[0]
```

or like this:

```python
for regex, hash_types in HASH_TYPE_REGEX.iteritems():
    if regex.match(hash_to_verify):
        if verbose is True:
            LOGGER.debug("Testing: {}".format(hash_types))
        return hash_types if least_likely else hash_types[0]
```

**Comment by Ekultek** [comment]
Oops, forgot to remove that, knew I had some commits to push and forgot to check all of them lol my bad, do what you need to do 

- Thomas Perkins

**Comment by delirious-lettuce** [comment]
@Ekultek ,

I was asking because I don't know which way you want it to be. If you want the log to show every different hash that's being tested, it seems like having the message above the regex check if preferable. But if you want only the matches shown, having the message underneath the regex check if preferable.

Just guessing, but the message seems to imply you want them all shown, not just the matches. In other words, remove the log message from inside of the regex check and just leave the one above the regex check...?

**Comment by Ekultek** [comment]
As I said, you've pushed enough to this project for me to trust what you think is best. You can make the choice on this one man, completely up to you. I would prefer it to show all hashes, however, that would slow things down a bit and I don't want that. So whatever you think is best in game for 

- Thomas Perkins

**Comment by delirious-lettuce** [comment]
@Ekultek ,

I chose to leave all the hashes being logged (as you preferred). It seems like if this is found to be a performance bottleneck, it could always be moved underneath to only show the matches.

As they say, premature optimization is the root of all evil!

**Comment by Ekultek** [comment]
I'd like to talk to you about granting you access to the repo do you have slack?

**Comment by delirious-lettuce** [comment]
No, slack but I guess I could make one. I use Gitter quite a bit to talk to people from github though.

**Comment by Ekultek** [comment]
Get slack and lemme know your username I'll send you a request

- Thomas Perkins

**Comment by delirious-lettuce** [comment]
Ok, I'll go try and get signed up.

**Comment by Ekultek** [comment]
Sounds good bud, lemme know when you're done and I'll send the info to you

- Thomas Perkins

**Comment by delirious-lettuce** [comment]
@delirious.lettuce

I'm not sure if you need the @ sign or whatever.

**Comment by Ekultek** [comment]
Need the email you signed up with

- Thomas Perkins

**Comment by delirious-lettuce** [comment]
Oh sorry.

delirious.lettuce@gmail.com

**Comment by Ekultek** [comment]
Sent the invite

- Thomas Perkins

**Pull request merged**
